name: Latest web checks

on:
  schedule:
    - cron: "5/30 6-22 * * *"
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies and scrape checks
        run: npm install && npm run checks
      - name: Commit and push if changes occured
        id: try-commit-push
        # multiline 'additions' are escaped according to https://github.community/t/set-output-truncates-multiline-strings/16852/2
        # also truncating additions to 3800 chars because of telegram msg size limit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest checks data: ${timestamp}" || exit 0
          git push
          additions="$(git diff -w HEAD^ HEAD ':*.md')"
                    additions="$(git diff HEAD^ HEAD --name-only --diff-filter=AM --exit-code ':*.md' | sed -r 's/(.*)\.md$/https\:\/\/github\.com\/chiviteam\/web-alerts\/blob\/main\/\1\.md/')"
          additions="${additions//'%'/'%25'}"
          additions="${additions//$'\n'/'%0A'}"
          additions="${additions//$'\r'/'%0D'}"
          echo "::set-output name=checks-changes::${additions:0:3800}"
          echo "::set-output name=checks-url::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"
      - name: Notify telegram
        uses: appleboy/telegram-action@master
        if: ${{ success() && steps.try-commit-push.outputs.checks-changes != ''}}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "[Check alert - changes](${{steps.try-commit-push.outputs.checks-url}}):\n${{steps.try-commit-push.outputs.checks-changes}}\n[See changes on github](${{steps.try-commit-push.outputs.checks-url}})"
          format: markdown